### PR TITLE
Learning path translations

### PR DESCRIPTION
**Pull request by tsadler1988**
Follow up from #32. 

image

The translated articles are available via a drop down menu, but navigation does not work correctly due to missing index pages. I will need help from Russian, German, Chinese, Japanese, and Italian speakers to create these index pages (as per e.g. `content/learn/learning-path/introduction/_index.ru.md`).

### CODE REVIEW

**Comment by voborgus** [comment]
Great! @tsadler1988 can we have a small instruction where we need to place language index files?

**Comment by tsadler1988** [comment]
> Great! @tsadler1988 can we have a small instruction where we need to place language index files?

Hi @voborgus, I've thought about this, and I think we should generate these pages from the [Learning Path scripts](https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/scripts). This will require some additional files in the Learning Path, but will ensure future translations get their required _index files.

I will add English placeholders for now, and reach out to Learning Path translators to get them translated.

**Comment by tsadler1988** [comment]
I think this is good enough to merge now, although there are still some outstanding issues with navigation when you switch language. You can see on the below screenshot of the German Introduction section that the navigation breadcrumbs are 'InnerSource Commons / Learns' rather than 'InnerSource Commons / Learn / Learning Path'

image

I _think_ this is a broader problem with the website, rather than something specific to the Learning Path, so we should merge this and fix navigation under a separate issue. Happy to be proved wrong or outvoted though!

**Comment by voborgus** [comment]
Thanks for making this happen, will fix all issues in other issues :)

**Pull request merged**
