### PR TITLE
InnerSource in Action

### PR DESCRIPTION
**Pull request by clcoffey**
A first attempt at the InnerSource in Action page. https://github.com/InnerSourceCommons/innersourcecommons.net/issues/22

I added the logos in an image at the top and the quotes are structured on 3 columns underneath.

I think this should be ok for the first pass/ MVP however in the long run we need to figure out a solution for adding more logos to the page.

### CODE REVIEW

**Comment by voborgus** [comment]
awesome! Can you please remove the `static/images/learn/logos/huawei_logo.svg` file since it's not used?

**Comment by claredillon** [comment]
Agreed at the marketing meeting that this will be moved under the new Community folder/menu item.

**Comment by clcoffey** [comment]
Done

**Comment by voborgus** [comment]
thanks a lot!

**Pull request merged**
