### PR TITLE
Learning path content

### PR DESCRIPTION
**Pull request by tsadler1988**
First pass at #28. This needs a bit more thought before it can merged:
- ~Need thumbnails for each video, rather than using section introduction thumbnail everywhere~
- We should be generating these pages with GitHub Actions on every change to https://github.com/InnerSourceCommons/InnerSourceLearningPath/ articles - more pertinent than on the old site where articles are retrieved from GitHub at run time
- ~Article body Is rendered to HTML, rather than Markdown - is this acceptable?~
- Translations - when I added translations per the example they got mixed in together with English pages
- ~_index pages are manually generated - is this acceptable?~
- ~In-article links currently go to old website~
- ~Article title is duplicated above and below the video - do we want this?~

### CODE REVIEW

**Comment by voborgus** [comment]
Big thanks for your contribution! A really good job.

> Need thumbnails for each video, rather than using section introduction thumbnail everywhere

Yep, will be great. The easiest but not so fancy way is to use [this service](http://www.get-youtube-thumbnail.com/).

> We should be generating these pages with GitHub Actions on every change to https://github.com/InnerSourceCommons/InnerSourceLearningPath/ articles - more pertinent than on the old site where articles are retrieved from GitHub at run time

Yep, and you can push them directly to the master to be able to automatically update the website.

> Article body Is rendered to HTML, rather than Markdown - is this acceptable?

We should check the correctness of the display, but in general, it's fully OK.

> Translations - when I added translations per the example they got mixed in together with English pages

In Hugo, there are [two ways](https://gohugo.io/content-management/multilingual/#translate-your-content) exists how to translate the content: by the multiple root directories and by the file extension in the same directory. I decided to go with second only because is too easy to forget about translations while they will be located too far from each other. But of course, we can decide to choose the first option.

> _index pages are manually generated - is this acceptable?

Yes, this needed only for letting Hugo know where is the [Branch Bundle](https://gohugo.io/content-management/page-bundles/).

> In-article links currently go to old website

If we want to do a very smooth move we can use redirects [in the new site](https://github.com/InnerSourceCommons/innersourcecommons.net/tree/master/content/redirects) and in [the old site](https://github.com/InnerSourceCommons/innersourcecommons.org/blob/master/pages/slack.md).

The easiest way in my opinion is to keep the links the same as we have right now with the old structure and change them only when we'll move the new version of the site to production.

> Article title is duplicated above and below the video - do we want this?

No. We can remove the second title from the generated file (preferable way, if possible, of course) or I can change the layout for the learning path section.

**Comment by tsadler1988** [comment]
Thanks for the feedback @voborgus! I've crossed out the resolved questions and will get to work on the outstanding points.

**Comment by tsadler1988** [comment]
> Need thumbnails for each video, rather than using section introduction thumbnail everywhere

Addressed this by using `https://img.youtube.com/vi/${videoId}/mqdefault.jpg`. However, I wonder whether there is a more appropriate image for the workbook links, as there is no corresponding video so they still use the intro video thumbnail.

> In-article links currently go to old website

Addressed this by running a script against the source files to update the links - see https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/369.

> Article title is duplicated above and below the video - do we want this?

Also addressed this in https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/369 - scripts now strip the duplicate title .

Still need to tackle translations and GitHub Actions, but perhaps these can be done under separate PRs?

**Comment by voborgus** [comment]
Let's merge it and see how it looks. Thanks so much for the contribution!

**Pull request merged**
