### PR TITLE
Board intro text

### PR DESCRIPTION
**Pull request by clcoffey**
I added a paragraph before the list of the Board Members. I made it a h4 as I felt like the normal text would get lost.

Addresses: https://github.com/InnerSourceCommons/innersourcecommons.net/issues/55

### CODE REVIEW

**Comment by voborgus** [comment]
Super! A little comment: the current text does not answer the question `why we have Board in place?`. So I mean if somebody reaches the site and he found this page it would be useful for them to have an answer to why we created the Board and what questions they solve.

**Comment by clcoffey** [comment]
I just saw this now... what do you think @claredillon ? Any idea of how to answer this question?

**Comment by claredillon** [comment]
Added in proposed text to this fork. Is that the right process. Text is included here as a back up: 

As a an IRS registered 501(c)(3) non-profit, the InnerSource Commons (ISC) is governed by a set of corporate bylaws like many companies. The Board of Directors sets the ISC's policy and appoints officers (e.g. Treasurer); various officers set and execute policy. The ISC Board is elected by the Membership on a yearly basis. ISC initially is incorporated in the US. As the community grows, we anticipate to found sister organizations in the European Union, Latin America, and other parts of the world.

**Review by voborgus — APPROVED** [review]
thanks for the improvements!

**Pull request merged**
